### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by Pranali3103**
I have added python files for gesture control mouse , please review it and merge it.

### CODE REVIEW

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
cant upload file like this.

**Comment by Pranali3103** [comment]
Okay , I'll change this, This wasn't final files , this was my daily work , Still the documentation part is remaining and all files are also yet to add.

**Comment by Pranali3103** [comment]
Do I need to add .ipynb files ? @sanjay-kv

**Comment by sanjay-kv** [comment]
> Do I need to add .ipynb files ? @sanjay-kv

yes

**Comment by Pranali3103** [comment]
Okay I'll add that.

**Pull request closed without merging**
