### PR TITLE
Added ResNet50 Model

### LINKED ISSUE #377: Adding ResNet50 Model
I want to add the ResNet50 model. Kindly assign this issue to me. Thank you.

### PR DESCRIPTION
**Pull request by Ishita-Jena**
## Description

I've added the resnet50 model with an accuracy of 78%.

Fixes #377

## Type of change

- [ ] Added a new machine learning frameworks, libraries or software.
- [Yes] Documentation update

## Checklist:

- [Yes] My code follows the style guidelines of this project
- [Yes] I have performed a self-review of my own code
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have made corresponding changes to the documentation
- [Yes] My changes generate no new warnings

### CODE REVIEW

**Comment by Ishita-Jena** [comment]
@sanjay-kv would u please review and merge my pr?

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
please add into a folder

**Comment by Ishita-Jena** [comment]
I've done the changes. Please check it out.

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
Could you explain this a bit to me. 
I understand restnet is a model. but on what data are we using. i can see code only no explanation. 
If you open the repo people creating folder library such as twitter scrape, which solves some issue on real time. so I'm trying to understand what we are solving here exactly,

**Comment by Ishita-Jena** [comment]
I used the ResNet50 model on the CIFAR-10 dataset, which consists of 60,000 32x32 images belonging to 10 different classes, including cat, dog, bird, airplane, and more. The problem we're solving is image classification, where the model learns to identify and categorize these images into their respective classes.

**Comment by Ishita-Jena** [comment]
Should I add the explanation to the code for more clarification?

**Comment by sanjay-kv** [comment]
yes please, i didnt understood much looking at it.

**Comment by Ishita-Jena** [comment]
I've added explanations and eda for more clarity. Please see if it's alright or more changes are required.

**Review by sanjay-kv — APPROVED** [review]

**Pull request merged**
