### PR TITLE
Credit Card Fraud Detection Model

### PR DESCRIPTION
**Pull request by PadmalathaKasireddy**
This PR introduces a Credit Card Fraud Detection model using machine learning techniques. The dataset used for this project is highly imbalanced, with legitimate transactions vastly outnumbering fraudulent ones. The primary objective is to accurately detect fraudulent transactions while addressing the challenges posed by the imbalanced dataset.

#### Key Features

1. **Exploratory Data Analysis (EDA)**:
    - Analysed the dataset to understand the distribution of features and the target variable.
    - Visualized the distribution of transaction amounts and transaction times.
    
image

image

   - Created a correlation heatmap to identify relationships between features.

2. **Data Preprocessing**:
3. **Handling Imbalanced Data**:
    - The dataset is highly imbalanced with only 0.2% fraudulent transactions.
    image

    - Applied Synthetic Minority Over-Sampling Technique (SMOTE) to create a balanced training dataset by generating synthetic samples for the minority class.
4. **Model Training and Evaluation**:
    - Trained and evaluated multiple machine learning models:
        - Logistic Regression
        - Decision Tree
        - Random Forest
        - Gradient Boosting Classifier
    - Compared models using key metrics such as accuracy, log loss, AUC-ROC, F1-score, and recall.
5. **Chosen Model**:
    - Selected the Gradient Boosting Classifier as the final model based on its performance metrics.
    - Gradient Boosting showed a good balance between precision and recall, and provided a high AUC-ROC score, indicating its effectiveness in distinguishing between legitimate and fraudulent transactions.
    
6. **Performance Metrics**:
    - **AUC-ROC Score**: 0.9670
    - **F1-score**: 0.2884
    - **Recall**: 0.8444
7. **ROC Curve**:
    - Plotted the Receiver Operating Characteristic (ROC) curve to visualize the model's performance in distinguishing between legitimate and fraudulent transactions.
image

### CODE REVIEW

**Comment by PadmalathaKasireddy** [comment]
@sanjay-kv 
Please review this PR and provide me with any suggestions.
Thank you.

**Comment by Jatin9826** [comment]
please assign me this project i want to contribute this and i want to do some changes in this

**Comment by Jatin9826** [comment]
assign me this project

**Review by sanjay-kv — APPROVED** [review]

**Comment by Jatin9826** [comment]
I completed the task you can see on my GitHub .
https://github.com/Jatin9826/Credit-card-fraud-detection-using-machine-learning

**Pull request merged**
