### PR TITLE
Add AI Gesture Control project using OpenCV

### PR DESCRIPTION
**Pull request by ashis2004**
### Description
This pull request adds an AI Gesture Control project using OpenCV.

### Features
- Real-time hand tracking using cvzone's HandDetector module.
- Virtual drag and drop functionality based on fingertip positions.
- Integration of OpenCV for video capture and image manipulation.

### How to Use
1. Run the script.
2. Use your index finger and thumb to drag and drop the virtual object in the webcam feed.

### Why This is Useful
This project demonstrates the use of computer vision for interactive applications and can serve as a foundation for more advanced AR projects.
### Demonstration
image

### CODE REVIEW

**Comment by ashis2004** [comment]
@sanjay-kv sir please check it

**Comment by ashis2004** [comment]
Pls check it once sir @sanjay-kv

**Comment by sanjay-kv** [comment]
Im not able to review this file due to large amount of files you pushed, usually all the main data file will be stored either in cloud , or drive. github cant handle

**Comment by sanjay-kv** [comment]
image

**Pull request closed without merging**
